name: Kuai Fang
title: Hydropunk 2020
description: 


collections:
  authors:
    output: true
  chapters:
    output: true


defaults:
  - scope:
      path: ""
      name: "index"
    values:
      layout: "index"

